Repository Rodrigues-Developers/silver-catalog, pull requests merged in 2024-12, with the labels that each got.

#27 Connect back and front
  api-server.js
  package-lock.json
  package.json
  server.js
  src/app/api.service.ts
  src/app/pages/external-api/external-api.component.html
  src/app/pages/external-api/external-api.component.ts
  src/index.html
  src/main.ts
Labels: enhancement, Front

#29 feat: update node version
  .github/workflows/release.yml
Labels: documentation, enhancement

#30 feat: update branch name
  .releaserc.json
Labels: documentation, enhancement

#31 feat: update permission
  .github/workflows/release.yml
Labels: documentation, enhancement

#36 Feature/product list
  CHANGELOG.md
  src/app/api.service.ts
  src/app/app.component.html
  src/app/components/hero/hero.component.html
  src/app/components/hero/hero.component.less
  src/app/components/hero/hero.component.spec.ts
  src/app/components/hero/hero.component.ts
  src/app/components/home-content/home-content.component.html
  src/app/components/home-content/home-content.component.spec.ts
  src/app/components/home-content/home-content.component.ts
  src/app/components/main-banner/main-banner.component.html
  src/app/components/main-banner/main-banner.component.less
  src/app/components/main-banner/main-banner.component.spec.ts
  src/app/components/main-banner/main-banner.component.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.less
  src/app/components/product-list/product-list.component.html
  src/app/components/product-list/product-list.component.less
  src/app/components/product-list/product-list.component.spec.ts
  src/app/components/product-list/product-list.component.ts
  src/app/interfaces/products.interface.ts
  src/app/pages/external-api/external-api.component.ts
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.ts
  src/app/shared/pipes/capitalize.pipe.ts
  src/app/shared/styles/breakpoints.less
  src/app/shared/styles/global_colors.less
  src/app/utils/strings.ts
  src/assets/ring_sample2.jpg
  src/styles.less
Labels: enhancement, Front

#37 Issue 5 create sidebar
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.less
  src/app/app.component.ts
  src/app/components/footer/footer.component.less
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.less
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/footer/footer.component.less
  src/app/components/shared/footer/footer.component.spec.ts
  src/app/components/shared/footer/footer.component.ts
  src/app/components/shared/loading/loading.component.html
  src/app/components/shared/loading/loading.component.less
  src/app/components/shared/loading/loading.component.spec.ts
  src/app/components/shared/loading/loading.component.ts
  src/app/components/shared/nav-bar/nav-bar.component.html
  src/app/components/shared/nav-bar/nav-bar.component.less
  src/app/components/shared/nav-bar/nav-bar.component.spec.ts
  src/app/components/shared/nav-bar/nav-bar.component.ts
  src/app/components/shared/side-bar/side-bar.component.html
  src/app/components/shared/side-bar/side-bar.component.less
  src/app/components/shared/side-bar/side-bar.component.spec.ts
  src/app/components/shared/side-bar/side-bar.component.ts
  src/app/components/shared/styles/colors.less
  src/app/components/shared/styles/media-query.less
  src/app/pages/home/home.component.ts
  src/assets/logo-ags-nome.png
  src/assets/logo-ags.png
  src/custom-theme.scss
  src/favicon.ico
  src/index.html
  src/main.ts
  src/styles.less
Labels: enhancement, Front, Style

#38 style: adjusted the navbar to be absolue and fixed a minor bug when changing from mobile to desktop width
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/components/shared/nav-bar/nav-bar.component.less
Labels: Style

#43 feat(all!) Changed authencation to use firebase
  .env
  .eslintrc.json
  .github/workflows/azure-static-web-apps-black-glacier-0a885420f.yml
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  angular.json
  e2e/src/app.e2e-spec.ts
  karma.conf.js
  package-lock.json
  package.json
  src/app/api.service.spec.ts
  src/app/api.service.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/main-banner/main-banner.component.ts
  src/app/components/product-list/product-list.component.html
  src/app/components/product-list/product-list.component.less
  src/app/components/product-list/product-list.component.ts
  src/app/components/shared/loading/loading.component.html
  src/app/components/shared/loading/loading.component.less
  src/app/components/shared/nav-bar/nav-bar.component.html
  src/app/components/shared/nav-bar/nav-bar.component.less
  src/app/components/shared/nav-bar/nav-bar.component.ts
  src/app/components/shared/side-bar/side-bar.component.html
  src/app/components/shared/side-bar/side-bar.component.ts
  src/app/core/guards/auth.guard.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/firebase-storage.service.spec.ts
  src/app/core/services/firebase-storage.service.ts
  src/app/interfaces/firebase.interface.ts
  src/app/interfaces/products.interface.ts
  src/app/pages/error/error.component.html
  src/app/pages/error/error.component.ts
  src/app/pages/external-api/external-api.component.html
  src/app/pages/external-api/external-api.component.spec.ts
  src/app/pages/external-api/external-api.component.ts
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.ts
  src/app/pages/product-management/product-management.component.html
  src/app/pages/product-management/product-management.component.less
  src/app/pages/product-management/product-management.component.spec.ts
  src/app/pages/product-management/product-management.component.ts
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.component.ts
  src/custom-theme.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/main.ts
  src/styles.less
  tsconfig.app.json
  tsconfig.json
Labels: Front, Business
