Repository Rodrigues-Developers/silver-catalog, pull requests merged in 2025-03, with the labels that each got.

#79 Add search functionality for products in category pages
  src/app/api.service.ts
  src/app/components/product-list/product-list.component.html
  src/app/components/product-list/product-list.component.ts
  src/app/components/shared/nav-bar/nav-bar.component.html
  src/app/components/shared/side-bar/side-bar.component.html
  src/app/components/shared/side-bar/side-bar.component.less
  src/app/components/shared/side-bar/side-bar.component.ts
  src/app/core/services/filter.service.ts
Labels: enhancement, Front

#83 feat(azure.md): how to publish to azure
  .github/workflows/azure-static-web-apps-zealous-coast-0d8c38f0f.yml
  Manual publish to azure.md
Labels: Front, Business

#85 feat(product-management): added option to crud additional images
  src/app/components/product-details/product-details.component.html
  src/app/components/product-details/product-details.component.less
  src/app/components/product-details/product-details.component.ts
  src/app/core/services/firebase-storage.service.ts
  src/app/interfaces/products.interface.ts
  src/app/pages/product-management/product-management.component.html
  src/app/pages/product-management/product-management.component.less
  src/app/pages/product-management/product-management.component.ts
Labels: enhancement, Front

#87 feat(horizontal-slider): added category filter to horizontal and banner link
  src/app/components/category-details/category-details.component.html
  src/app/components/category-details/category-details.component.ts
  src/app/components/horizontal-slider/horizontal-slider.component.html
  src/app/components/horizontal-slider/horizontal-slider.component.less
  src/app/components/horizontal-slider/horizontal-slider.component.ts
  src/app/components/shared/side-bar/side-bar.component.ts
  src/app/interfaces/banner.interface.ts
  src/app/pages/banner-management/banner-management.component.html
  src/app/pages/banner-management/banner-management.component.ts
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.ts
Labels: enhancement, Front

#88 Fix search functionality and improve responsiveness
  src/app/api.service.ts
  src/app/components/category-details/category-details.component.less
  src/app/components/category-details/category-details.component.ts
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-list/product-list.component.ts
  src/app/components/shared/side-bar/side-bar.component.html
  src/app/components/shared/side-bar/side-bar.component.less
  src/app/components/shared/side-bar/side-bar.component.ts
  src/app/core/services/filter.service.ts
  src/app/interfaces/category.interface.ts
  src/app/shared/styles/breakpoints.less
Labels: bug, Front
